version: '3.8'

services:
  api-under-test:
    image: your-api-image:test
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=testing

  test-runner:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    command: make test
    depends_on:
      - api-under-test